# Uncomment/fill the channel(s) you've set up. See:
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# github: [yotam707]        # requires GitHub Sponsors enabled for the account
# open_collective: nemus
# ko_fi: your-handle
# custom: ["https://me-public.github.io/nemus/"]
