#!/usr/bin/env python3
"""
workspace-table.py — Nemus status-line extension for Claude Code
(auto-generated by nemus)

Outputs ONLY the workspace repo table (branch · PR · CI · dirty state).
Claude Code already renders model / cost / context itself, so this script
adds only what it doesn't show.

Configure in ~/.claude/settings.json:
  "statusLine": {
    "type": "command",
    "command": "~/.nemus-table.py",
    "padding": 0
  }

Claude Code passes session data as JSON on stdin.
"""

import hashlib
import json
import os
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

# ─── Cache ───────────────────────────────────────────────────────────────────
CACHE_FILE = Path.home() / ".nemus" / "pr-status.json"
CACHE_TTL = 300  # seconds

# ─── ANSI helpers ─────────────────────────────────────────────────────────────
RESET   = "\033[0m"
BOLD    = "\033[1m"
DIM     = "\033[2m"
CYAN    = "\033[38;5;87m"
BLUE    = "\033[38;5;75m"
MAGENTA = "\033[38;5;213m"
GREEN   = "\033[38;5;120m"
YELLOW  = "\033[38;5;221m"
RED     = "\033[38;5;203m"
GRAY    = "\033[38;5;245m"
PURPLE  = "\033[38;5;141m"


def color(text: str, c: str) -> str:
    return f"{c}{text}{RESET}"


def hyperlink(text: str, url: str | None) -> str:
    if not url:
        return text
    return f"\033]8;;{url}\033\\{text}\033]8;;\033\\"


# ─── Cache helpers ────────────────────────────────────────────────────────────
def load_cache() -> dict:
    try:
        return json.loads(CACHE_FILE.read_text())
    except Exception:
        return {}


def save_cache(cache: dict) -> None:
    try:
        CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
        CACHE_FILE.write_text(json.dumps(cache))
    except Exception:
        pass


# ─── Git / PR helpers ─────────────────────────────────────────────────────────
def repo_web_url(cwd: str) -> str | None:
    try:
        r = subprocess.run(
            ["git", "-C", cwd, "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=0.3,
        )
        if r.returncode != 0:
            return None
        url = r.stdout.strip()
        if url.startswith("git@"):
            host, path = url[4:].split(":", 1)
            url = f"https://{host}/{path}"
        if url.endswith(".git"):
            url = url[:-4]
        return url
    except Exception:
        return None


def pr_info(cwd: str, branch: str) -> dict:
    """Return cached PR info, firing a background refresh if stale."""
    repo_url = repo_web_url(cwd)
    if not repo_url:
        return {"url": None, "fallback": None, "number": None,
                "state": None, "isDraft": None, "ci": None}
    key = hashlib.sha1(f"{repo_url}@{branch}".encode()).hexdigest()
    cache = load_cache()
    entry = cache.get(key)
    now = time.time()
    fresh = entry and now - entry.get("ts", 0) < CACHE_TTL
    fallback = f"{repo_url}/tree/{branch}"
    if not fresh:
        try:
            subprocess.Popen(
                [sys.executable, str(Path(__file__).resolve()), "--refresh-pr", key, cwd, branch],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL, start_new_session=True,
            )
        except Exception:
            pass
    e = entry or {}
    return {
        "url": e.get("url"),
        "fallback": fallback,
        "number": e.get("number"),
        "state": e.get("state"),
        "isDraft": e.get("isDraft"),
        "ci": e.get("ci"),
    }


def refresh_pr(key: str, cwd: str, branch: str) -> None:
    info: dict = {"url": None, "number": None, "state": None,
                  "isDraft": None, "ci": None}
    try:
        r = subprocess.run(
            ["gh", "pr", "view", "--json",
             "url,number,state,isDraft,statusCheckRollup"],
            capture_output=True, text=True, timeout=10, cwd=cwd,
        )
        if r.returncode == 0 and r.stdout.strip():
            data = json.loads(r.stdout)
            info["url"] = data.get("url")
            info["number"] = data.get("number")
            info["state"] = data.get("state")
            info["isDraft"] = data.get("isDraft")
            # Summarise CI rollup
            rollup = data.get("statusCheckRollup") or []
            info["ci"] = _rollup_ci(rollup)
    except Exception:
        pass
    cache = load_cache()
    cache[key] = {**info, "ts": time.time()}
    save_cache(cache)


def _rollup_ci(rollup: list) -> str | None:
    if not rollup:
        return None
    has_fail = has_pending = False
    for c in rollup:
        s = (c.get("state") or c.get("conclusion") or c.get("status") or "").upper()
        if s in ("FAILURE", "TIMED_OUT", "CANCELLED", "ERROR"):
            has_fail = True
        elif s in ("PENDING", "IN_PROGRESS", "QUEUED", "", "EXPECTED"):
            has_pending = True
    if has_fail:
        return "failure"
    if has_pending:
        return "pending"
    return "success"


def git_info(cwd: str) -> tuple[str, int | None] | None:
    try:
        r = subprocess.run(
            ["git", "-C", cwd, "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, timeout=1.0,
        )
        if r.returncode != 0:
            return None
        branch = r.stdout.strip()
    except Exception:
        return None
    dirty: int | None = None
    try:
        s = subprocess.run(
            ["git", "-C", cwd, "status", "--porcelain"],
            capture_output=True, text=True, timeout=2.0,
        )
        if s.returncode == 0:
            dirty = len([l for l in s.stdout.splitlines() if l.strip()])
    except Exception:
        pass
    return branch, dirty


# ─── Workspace discovery ───────────────────────────────────────────────────────
DEFAULT_BRANCHES = {"main", "master", "develop", "production", "trunk"}

CI_ICON   = {"success": "✓", "failure": "✗", "pending": "◌"}
CI_COLOR  = {"success": GREEN, "failure": RED, "pending": YELLOW}
PR_ICONS  = {
    "open":   "\ue725",  # nf-cod-git_pull_request
    "draft":  "\uea64",  # nf-oct-git_pull_request_draft
    "merged": "\uea6a",  # nf-oct-git_merge
    "closed": "\ue729",  # nf-cod-git_pull_request_closed
}


def find_workspace(cwd: str) -> tuple[Path, dict] | None:
    p = Path(cwd).resolve()
    for candidate in [p, *p.parents]:
        meta = candidate / ".workspace-meta.json"
        if meta.is_file():
            try:
                data = json.loads(meta.read_text())
                return candidate, data
            except Exception:
                return None
    return None


def gather_repo_row(repo_path: Path, is_active: bool) -> dict:
    cwd_str = str(repo_path)
    g = git_info(cwd_str)
    name = repo_path.name
    if not g:
        return {"active": is_active, "name": name, "branch": None,
                "branch_url": None, "pr": None, "dirty": None, "no_git": True}
    branch, dirty = g
    pi = pr_info(cwd_str, branch)
    return {
        "active": is_active,
        "name": name,
        "branch": branch,
        "branch_url": pi.get("url") or pi.get("fallback"),
        "pr_num": pi.get("number"),
        "pr_url": pi.get("url"),
        "pr_state": pi.get("state"),
        "pr_draft": pi.get("isDraft"),
        "pr_ci": pi.get("ci"),
        "dirty": dirty,
        "no_git": False,
    }


# ─── Cell renderers ────────────────────────────────────────────────────────────
def pr_plain(row: dict) -> str:
    if row["no_git"] or not row.get("pr_num"):
        return "—" if not row["no_git"] and row.get("branch") else ""
    s = f"#{row['pr_num']}"
    if row.get("pr_draft"):       s += " draft"
    elif row.get("pr_state") == "MERGED":  s += " merged"
    elif row.get("pr_state") == "CLOSED":  s += " closed"
    ci = row.get("pr_ci")
    if ci:
        s += f"  {CI_ICON.get(ci, '')}"
    return s


def pr_styled(row: dict) -> str:
    if row["no_git"] or not row.get("pr_num"):
        return color("—", GRAY) if not row["no_git"] and row.get("branch") else ""
    num = f"#{row['pr_num']}"
    draft = row.get("pr_draft")
    state = row.get("pr_state", "OPEN")
    icon = PR_ICONS.get("draft" if draft else state.lower(), PR_ICONS["open"])
    if draft:      c = GRAY
    elif state == "MERGED":  c = PURPLE
    elif state == "CLOSED":  c = RED
    else:          c = GREEN
    label = f"{icon} {num} {'draft' if draft else state.lower()}"
    ci = row.get("pr_ci")
    ci_part = f"  {color(CI_ICON.get(ci,''), CI_COLOR.get(ci, GRAY))}" if ci else ""
    return hyperlink(color(label, c), row.get("pr_url")) + ci_part


def dirty_plain(row: dict) -> str:
    if row["no_git"]:      return "(no git)"
    if row["dirty"] is None:  return "*?"
    return f"*{row['dirty']}" if row["dirty"] > 0 else ""


def dirty_styled(row: dict) -> str:
    if row["no_git"]:         return color("(no git)", GRAY)
    if row["dirty"] is None:  return color("*?", GRAY)
    return color(f"*{row['dirty']}", RED) if row["dirty"] > 0 else ""


# ─── Table renderer ────────────────────────────────────────────────────────────
def render_repo_table(rows: list[dict]) -> list[str]:
    headers = ("REPO", "BRANCH", "PR", "DIRTY")
    plain_rows = [(r["name"], r.get("branch") or "", pr_plain(r), dirty_plain(r))
                  for r in rows]
    plain_rows.insert(0, headers)
    widths = [max(len(p[i]) for p in plain_rows) for i in range(4)]

    def pad(s: str, w: int) -> str:
        return s + " " * (w - len(s))

    header = "  " + "  ".join(
        color(pad(h, widths[i]), DIM + GRAY) for i, h in enumerate(headers)
    )

    result = [header]
    for r in rows:
        marker = color("▸ ", PURPLE) if r["active"] else "  "
        name_c = PURPLE + BOLD if r["active"] else BLUE
        name_cell = color(r["name"], name_c if not r["no_git"] else DIM + GRAY)
        name_cell += " " * (widths[0] - len(r["name"]))

        br_plain = r.get("branch") or ""
        br_styled = (hyperlink(color(br_plain, MAGENTA), r.get("branch_url"))
                     if br_plain else "")
        br_cell = br_styled + " " * (widths[1] - len(br_plain))

        pp = pr_plain(r)
        pr_cell = pr_styled(r) + " " * (widths[2] - len(pp))

        dp = dirty_plain(r)
        d_cell = dirty_styled(r) + " " * (widths[3] - len(dp))

        result.append(f"{marker}{name_cell}  {br_cell}  {pr_cell}  {d_cell}".rstrip())
    return result


# ─── Main ─────────────────────────────────────────────────────────────────────
def main() -> None:
    """
    Claude Code calls this script and shows whatever we write to stdout
    as the statusLine — an *additional* line shown below the editor.
    Claude Code's own header (model · tokens · cost) is always shown
    regardless of what we output here.

    Behaviour contract:
    - Not in a workspace  → output nothing  (CC shows its default footer)
    - In workspace, all repos on default branch → output nothing
    - In workspace with feature-branch repos  → output the repo table only

    We NEVER output model info, cost, or anything that duplicates CC's
    own display. We NEVER modify the user's existing styling.
    """
    try:
        data = json.load(sys.stdin)
    except Exception:
        data = {}

    cwd = (data.get("workspace") or {}).get("current_dir") or os.getcwd()
    ws = find_workspace(cwd)

    if not ws:
        # Not in a workspace — output nothing so CC's default footer is shown unchanged.
        return

    ws_path, ws_meta = ws

    # Find which repo (if any) is currently active
    active_repo: str | None = None
    try:
        rel = Path(cwd).resolve().relative_to(ws_path)
        if rel.parts:
            active_repo = rel.parts[0]
    except ValueError:
        pass

    repo_tasks = []
    for repo in ws_meta.get("repositories") or []:
        dir_name = repo.get("directoryName") or repo.get("name")
        if not dir_name:
            continue
        repo_path = ws_path / dir_name
        if not repo_path.is_dir():
            continue
        repo_tasks.append((repo_path, dir_name == active_repo))

    if not repo_tasks:
        return

    max_workers = min(8, len(repo_tasks))
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        rows = list(ex.map(lambda t: gather_repo_row(*t), repo_tasks))

    # Filter: only repos on non-default branches (toggle not available in CC)
    rows = [r for r in rows if r.get("branch")
            and r["branch"] not in DEFAULT_BRANCHES]

    if not rows:
        # All repos are on default branches — nothing interesting to show.
        # Output nothing to preserve CC's default footer.
        return

    # Output ONLY the table. CC's model/cost header is shown above this independently.
    sys.stdout.write("\n".join(render_repo_table(rows)))


if __name__ == "__main__":
    if len(sys.argv) >= 4 and sys.argv[1] == "--refresh-pr":
        refresh_pr(sys.argv[2], sys.argv[3], sys.argv[4] if len(sys.argv) > 4 else "")
    else:
        main()
