import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { installPiExtensions, uninstallPiExtensions, getPiExtensionStatus } from './pi-extensions';

describe('Pi extensions', () => {
  let tmpDir: string;
  let extensionsDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-ext-test-'));
    extensionsDir = path.join(tmpDir, '.pi', 'agent', 'extensions');
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  describe('installPiExtensions', () => {
    it('creates the extensions directory if it does not exist', () => {
      expect(fs.existsSync(extensionsDir)).toBe(false);
      installPiExtensions(extensionsDir);
      expect(fs.existsSync(extensionsDir)).toBe(true);
    });

    it('installs all managed extensions', () => {
      installPiExtensions(extensionsDir);

      const files = fs.readdirSync(extensionsDir);
      expect(files).toContain('ws-permission-sync.ts');
      expect(files).toContain('ws-review-reminder.ts');
      expect(files).toContain('ws-permissions-gate.ts');
    });

    it('installed extensions contain the managed marker', () => {
      installPiExtensions(extensionsDir);

      for (const file of fs.readdirSync(extensionsDir)) {
        const content = fs.readFileSync(path.join(extensionsDir, file), 'utf-8');
        expect(content).toContain('auto-generated by workspace-manager');
      }
    });

    it('permission-sync extension has the script path replaced', () => {
      installPiExtensions(extensionsDir);

      const content = fs.readFileSync(
        path.join(extensionsDir, 'ws-permission-sync.ts'),
        'utf-8'
      );
      // Should not contain the placeholder
      expect(content).not.toContain('__SYNC_PERMISSIONS_SCRIPT__');
      // Should contain an actual path
      expect(content).toContain('sync-permissions.sh');
    });

    it('review-reminder extension references cache directory', () => {
      installPiExtensions(extensionsDir);

      const content = fs.readFileSync(
        path.join(extensionsDir, 'ws-review-reminder.ts'),
        'utf-8'
      );
      expect(content).toContain('.workspace-manager-cache');
      expect(content).toContain('last-permission-review');
    });

    it('permissions-gate extension has dangerous patterns', () => {
      installPiExtensions(extensionsDir);

      const content = fs.readFileSync(
        path.join(extensionsDir, 'ws-permissions-gate.ts'),
        'utf-8'
      );
      expect(content).toContain('rm\\s+-rf');
      expect(content).toContain('isToolCallEventType');
    });

    it('is idempotent — installing twice overwrites cleanly', () => {
      installPiExtensions(extensionsDir);
      const firstFiles = fs.readdirSync(extensionsDir).sort();

      installPiExtensions(extensionsDir);
      const secondFiles = fs.readdirSync(extensionsDir).sort();

      expect(firstFiles).toEqual(secondFiles);
    });

    it('does not touch non-managed files', () => {
      fs.mkdirSync(extensionsDir, { recursive: true });
      fs.writeFileSync(
        path.join(extensionsDir, 'my-custom-extension.ts'),
        '// custom'
      );

      installPiExtensions(extensionsDir);

      expect(
        fs.readFileSync(path.join(extensionsDir, 'my-custom-extension.ts'), 'utf-8')
      ).toBe('// custom');
    });
  });

  describe('uninstallPiExtensions', () => {
    it('removes all managed extensions', () => {
      installPiExtensions(extensionsDir);
      expect(fs.readdirSync(extensionsDir).length).toBeGreaterThan(0);

      uninstallPiExtensions(extensionsDir);

      expect(fs.readdirSync(extensionsDir).length).toBe(0);
    });

    it('does not remove non-managed extensions', () => {
      installPiExtensions(extensionsDir);
      fs.writeFileSync(
        path.join(extensionsDir, 'my-custom-extension.ts'),
        '// custom extension'
      );

      uninstallPiExtensions(extensionsDir);

      const remaining = fs.readdirSync(extensionsDir);
      expect(remaining).toEqual(['my-custom-extension.ts']);
    });

    it('removes files with managed marker even if renamed', () => {
      installPiExtensions(extensionsDir);

      // Rename a managed extension
      fs.renameSync(
        path.join(extensionsDir, 'ws-permission-sync.ts'),
        path.join(extensionsDir, 'renamed-sync.ts')
      );

      uninstallPiExtensions(extensionsDir);

      // renamed file should also be removed (has marker)
      expect(fs.readdirSync(extensionsDir).length).toBe(0);
    });

    it('handles non-existent directory gracefully', () => {
      expect(() => uninstallPiExtensions('/nonexistent/path')).not.toThrow();
    });
  });

  describe('getPiExtensionStatus', () => {
    it('reports all missing when nothing is installed', () => {
      fs.mkdirSync(extensionsDir, { recursive: true });

      const status = getPiExtensionStatus(extensionsDir);
      expect(status.installed).toHaveLength(0);
      expect(status.missing.length).toBeGreaterThan(0);
      expect(status.missing).toContain('ws-permission-sync.ts');
      expect(status.missing).toContain('ws-review-reminder.ts');
      expect(status.missing).toContain('ws-permissions-gate.ts');
    });

    it('reports all installed after installation', () => {
      installPiExtensions(extensionsDir);

      const status = getPiExtensionStatus(extensionsDir);
      expect(status.missing).toHaveLength(0);
      expect(status.installed).toContain('ws-permission-sync.ts');
      expect(status.installed).toContain('ws-review-reminder.ts');
      expect(status.installed).toContain('ws-permissions-gate.ts');
    });

    it('reports partial when some are missing', () => {
      installPiExtensions(extensionsDir);

      // Delete one
      fs.unlinkSync(path.join(extensionsDir, 'ws-review-reminder.ts'));

      const status = getPiExtensionStatus(extensionsDir);
      expect(status.installed).not.toContain('ws-review-reminder.ts');
      expect(status.missing).toContain('ws-review-reminder.ts');
      expect(status.installed.length + status.missing.length).toBe(5);
    });
  });
});
