/**
 * Pi extension management — install/uninstall Pi extensions that replicate
 * Claude Code hooks and MCP functionality.
 *
 * Pi uses TypeScript extensions instead of:
 *   - settings.json hooks (Stop, SessionStart, PostToolUse)
 *   - .mcp.json / `claude mcp add` (MCP servers)
 *
 * This module generates and installs extensions from bundled templates.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { logSuccess, logInfo, logWarning } from './logger';

const PI_EXTENSIONS_DIR = path.join(os.homedir(), '.pi', 'agent', 'extensions');

/** Marker comment that identifies nemus managed extensions */
const MANAGED_MARKER = '(auto-generated by nemus)';

/**
 * Extension template definitions.
 * Each maps a template file to the installed extension filename,
 * with optional placeholder replacements.
 */
interface ExtensionTemplate {
  /** Template filename (relative to pi-extensions/ dir) */
  templateFile: string;
  /** Installed filename under ~/.pi/agent/extensions/ */
  installedName: string;
  /** Placeholder replacements: key => value */
  replacements?: Record<string, string>;
}

function getTemplatesDir(): string {
  // When compiled: dist/utils/ -> dist/pi-extensions/
  const distPath = path.resolve(__dirname, '..', 'pi-extensions');
  // When running from source: src/utils/ -> src/pi-extensions/
  const srcPath = path.resolve(__dirname, '..', '..', 'src', 'pi-extensions');

  if (fs.existsSync(distPath)) return distPath;
  if (fs.existsSync(srcPath)) return srcPath;

  throw new Error('Could not find pi-extensions/ directory.');
}

function getSyncPermissionsScript(): string {
  const scriptPath = path.resolve(__dirname, '..', '..', 'sync-permissions.sh');
  if (fs.existsSync(scriptPath)) return scriptPath;
  throw new Error('Could not find sync-permissions.sh');
}

function getExtensionTemplates(options: { workspaceInputStatus?: boolean } = {}): ExtensionTemplate[] {
  let syncScript: string;
  try {
    syncScript = getSyncPermissionsScript();
  } catch {
    logWarning('Could not locate sync-permissions.sh — permission-sync extension will need manual path configuration');
    syncScript = ''; // Empty placeholder — user must configure manually
  }

  const templates: ExtensionTemplate[] = [
    {
      templateFile: 'permission-sync.ts.template',
      installedName: 'ws-permission-sync.ts',
      replacements: syncScript ? { '__SYNC_PERMISSIONS_SCRIPT__': syncScript } : {},
    },
    {
      templateFile: 'review-reminder.ts.template',
      installedName: 'ws-review-reminder.ts',
    },
    {
      templateFile: 'permissions-gate.ts.template',
      installedName: 'ws-permissions-gate.ts',
    },
    {
      templateFile: 'pr-fix-trigger.ts.template',
      installedName: 'ws-pr-fix-trigger.ts',
    },
  ];

  // Workspace input-status widget — enabled by default, opt-out via config
  if (options.workspaceInputStatus !== false) {
    templates.push({
      templateFile: 'workspace-input-status.ts.template',
      installedName: 'ws-workspace-input-status.ts',
    });
  }

  return templates;
}

/**
 * Install all nemus Pi extensions.
 * Idempotent — overwrites existing managed extensions with latest templates.
 *
 * @param extensionsDir Override the extensions directory (for testing).
 */
export function installPiExtensions(extensionsDir?: string, options: { workspaceInputStatus?: boolean } = {}): void {
  const targetDir = extensionsDir ?? PI_EXTENSIONS_DIR;

  let templatesDir: string;
  try {
    templatesDir = getTemplatesDir();
  } catch {
    logWarning('Could not find Pi extension templates — skipping');
    return;
  }

  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const templates = getExtensionTemplates(options);
  let installed = 0;

  for (const tpl of templates) {
    const templatePath = path.join(templatesDir, tpl.templateFile);
    if (!fs.existsSync(templatePath)) {
      logWarning(`Template not found: ${tpl.templateFile} — skipping`);
      continue;
    }

    let content = fs.readFileSync(templatePath, 'utf-8');

    // Apply replacements
    if (tpl.replacements) {
      for (const [placeholder, value] of Object.entries(tpl.replacements)) {
        content = content.replace(new RegExp(escapeRegex(placeholder), 'g'), value);
      }
    }

    const targetPath = path.join(targetDir, tpl.installedName);
    fs.writeFileSync(targetPath, content, 'utf-8');
    installed++;
  }

  if (installed > 0) {
    logSuccess(`Installed ${installed} Pi extension(s) in ${targetDir}`);
  }
}

/**
 * Uninstall nemus managed Pi extensions.
 * Only removes extensions that contain the managed marker or match
 * known installed names.
 *
 * @param extensionsDir Override the extensions directory (for testing).
 */
/**
 * Uninstall nemus managed Pi extensions.
 * Pass `onlyNames` to remove only specific extension files (for opt-out).
 *
 * @param extensionsDir Override the extensions directory (for testing).
 * @param options.onlyNames If set, only remove files in this list.
 */
export function uninstallPiExtensions(
  extensionsDir?: string,
  options?: { onlyNames?: string[] },
): void {
  const targetDir = extensionsDir ?? PI_EXTENSIONS_DIR;

  if (!fs.existsSync(targetDir)) return;

  const templates = getExtensionTemplates({ workspaceInputStatus: true });
  const knownNames = new Set(templates.map(t => t.installedName));
  const onlyNames = options?.onlyNames ? new Set(options.onlyNames) : null;
  let removed = 0;

  for (const file of fs.readdirSync(targetDir)) {
    if (!file.endsWith('.ts')) continue;

    // When onlyNames is set, skip files not in that list
    if (onlyNames && !onlyNames.has(file)) continue;

    const filePath = path.join(targetDir, file);

    // Remove if it matches a known managed name
    if (knownNames.has(file)) {
      fs.unlinkSync(filePath);
      removed++;
      continue;
    }

    // Also remove if it contains the managed marker (for renamed files)
    if (!onlyNames) {
      try {
        const content = fs.readFileSync(filePath, 'utf-8');
        if (content.includes(MANAGED_MARKER)) {
          fs.unlinkSync(filePath);
          removed++;
        }
      } catch { /* ignore read errors */ }
    }
  }

  if (removed > 0) {
    logSuccess(`Removed ${removed} Pi extension(s) from ${targetDir}`);
  }
}

/**
 * Check which managed Pi extensions are installed.
 */
export function getPiExtensionStatus(extensionsDir?: string): { installed: string[]; missing: string[] } {
  const targetDir = extensionsDir ?? PI_EXTENSIONS_DIR;
  const templates = getExtensionTemplates({ workspaceInputStatus: true });
  const installed: string[] = [];
  const missing: string[] = [];

  for (const tpl of templates) {
    const targetPath = path.join(targetDir, tpl.installedName);
    if (fs.existsSync(targetPath)) {
      installed.push(tpl.installedName);
    } else {
      missing.push(tpl.installedName);
    }
  }

  return { installed, missing };
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
